overrides:
  '@angular/common@<19.2.16': '>=19.2.16'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  koa@>=3.0.1 <3.0.3: '>=3.0.3'
  node-forge@<1.3.2: '>=1.3.2'
