import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { ClientTeamDto, CreateTeamDto, UpdateTeamDto, AddMemberDto } from '@ai-nx-starter/types';
import { BaseApiService } from '../../../services/base-api.service';
import { AppConfigService } from '../../../services/app-config.service';

/**
 * ApiTeamService - Angular service for TeamController
 * Auto-generated by tools/api-client-generator
 */
@Injectable({
  providedIn: 'root',
})
export class ApiTeamService extends BaseApiService {
  constructor(http: HttpClient, config: AppConfigService) {
    super(http, config);
  }

  /**
   * findAll - GET teams//
   *
   * @param limit - Query parameter
   * @param offset - Query parameter
   * @returns Observable<ClientTeamDto[]>
   */
  findAll(limit?: number, offset?: number): Observable<ClientTeamDto[]> {
    let params = new HttpParams();
    if (limit !== undefined) {
      params = params.set('limit', limit.toString());
    }
    if (offset !== undefined) {
      params = params.set('offset', offset.toString());
    }
    return this.http.get<ClientTeamDto[]>(`${this.BASE_URL}/teams`, { params });
  }

  /**
   * findById - GET teams/:id
   *
   * @param id - Param parameter
   * @returns Observable<ClientTeamDto>
   */
  findById(id: string): Observable<ClientTeamDto> {
    let url = `${this.BASE_URL}/teams/:id`;
    url = url.replace(':id', id.toString());
    return this.http.get<ClientTeamDto>(url);
  }

  /**
   * create - POST teams//
   *
   * @param createTeamDto - Body parameter
   * @returns Observable<ClientTeamDto>
   */
  create(createTeamDto: CreateTeamDto): Observable<ClientTeamDto> {
    return this.http.post<ClientTeamDto>(`${this.BASE_URL}/teams`, createTeamDto);
  }

  /**
   * update - PUT teams/:id
   *
   * @param id - Param parameter
   * @param updateTeamDto - Body parameter
   * @returns Observable<ClientTeamDto>
   */
  update(id: string, updateTeamDto: UpdateTeamDto): Observable<ClientTeamDto> {
    let url = `${this.BASE_URL}/teams/:id`;
    url = url.replace(':id', id.toString());
    return this.http.put<ClientTeamDto>(url, updateTeamDto);
  }

  /**
   * delete - DELETE teams/:id
   *
   * @param id - Param parameter
   * @returns Observable<void>
   */
  delete(id: string): Observable<void> {
    let url = `${this.BASE_URL}/teams/:id`;
    url = url.replace(':id', id.toString());
    return this.http.delete<void>(url);
  }

  /**
   * addMember - POST teams/:id/members
   *
   * @param id - Param parameter
   * @param addMemberDto - Body parameter
   * @returns Observable<ClientTeamDto>
   */
  addMember(id: string, addMemberDto: AddMemberDto): Observable<ClientTeamDto> {
    let url = `${this.BASE_URL}/teams/:id/members`;
    url = url.replace(':id', id.toString());
    return this.http.post<ClientTeamDto>(url, addMemberDto);
  }

  /**
   * removeMember - DELETE teams/:id/members/:userId
   *
   * @param id - Param parameter
   * @param memberId - Param parameter
   * @returns Observable<ClientTeamDto>
   */
  removeMember(id: string, memberId: string): Observable<ClientTeamDto> {
    let url = `${this.BASE_URL}/teams/:id/members/:userId`;
    url = url.replace(':id', id.toString());
    url = url.replace(':userId', memberId.toString());
    return this.http.delete<ClientTeamDto>(url);
  }
}
