import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import {} from '@ai-nx-starter/types';
import { BaseApiService } from '../../services/base-api.service';
import { AppConfigService } from '../../services/app-config.service';

/**
 * ApiHealthService - Angular service for HealthController
 * Auto-generated by tools/api-client-generator
 */
@Injectable({
  providedIn: 'root',
})
export class ApiHealthService extends BaseApiService {
  constructor(http: HttpClient, config: AppConfigService) {
    super(http, config);
  }

  /**
   * check - GET health//
   *
   * @returns Observable<{ status: string; timestamp: string; }>
   */
  check(): Observable<{ status: string; timestamp: string }> {
    return this.http.get<{ status: string; timestamp: string }>(`${this.BASE_URL}/health`);
  }
}
