import { ExampleDto } from '@ai-nx-starter/types';

export const SAMPLE_MEMBERS_DATA: ExampleDto[] = [
  {
    id: '1',
    name: 'John Doe',
    age: 30,
    email: 'john.doe@example.com',
    tags: ['developer', 'frontend'],
  },
  {
    id: '2',
    name: 'Jane Smith',
    age: 28,
    email: 'jane.smith@example.com',
    tags: ['designer', 'ui/ux'],
  },
  {
    id: '3',
    name: 'Bob Johnson',
    age: 35,
    email: 'bob.johnson@example.com',
    tags: ['backend', 'database'],
  },
  {
    id: '4',
    name: 'Alice Williams',
    age: 32,
    email: 'alice.williams@example.com',
    tags: ['project-manager', 'agile'],
  },
  {
    id: '5',
    name: 'Charlie Brown',
    age: 26,
    email: 'charlie.brown@example.com',
    tags: ['developer', 'react', 'javascript'],
  },
  {
    id: '6',
    name: 'Diana Prince',
    age: 29,
    email: 'diana.prince@example.com',
    tags: ['designer', 'branding', 'creative'],
  },
  {
    id: '7',
    name: 'Edward Miller',
    age: 41,
    email: 'edward.miller@example.com',
    tags: ['architect', 'senior', 'leadership'],
  },
  {
    id: '8',
    name: 'Fiona Davis',
    age: 24,
    email: 'fiona.davis@example.com',
    tags: ['intern', 'frontend', 'learning'],
  },
  {
    id: '9',
    name: 'George Wilson',
    age: 38,
    email: 'george.wilson@example.com',
    tags: ['devops', 'aws', 'infrastructure'],
  },
  {
    id: '10',
    name: 'Hannah Moore',
    age: 33,
    email: 'hannah.moore@example.com',
    tags: ['qa', 'testing', 'automation'],
  },
  {
    id: '11',
    name: 'Ian Taylor',
    age: 27,
    email: 'ian.taylor@example.com',
    tags: ['developer', 'python', 'backend'],
  },
  {
    id: '12',
    name: 'Julia Anderson',
    age: 31,
    email: 'julia.anderson@example.com',
    tags: ['product-owner', 'strategy', 'business'],
  },
  {
    id: '13',
    name: 'Kevin Thomas',
    age: 25,
    email: 'kevin.thomas@example.com',
    tags: ['developer', 'mobile', 'flutter'],
  },
  {
    id: '14',
    name: 'Laura Jackson',
    age: 36,
    email: 'laura.jackson@example.com',
    tags: ['designer', 'ux-research', 'user-experience'],
  },
  {
    id: '15',
    name: 'Michael White',
    age: 42,
    email: 'michael.white@example.com',
    tags: ['cto', 'leadership', 'strategy'],
  },
  {
    id: '16',
    name: 'Nina Harris',
    age: 28,
    email: 'nina.harris@example.com',
    tags: ['developer', 'vue', 'frontend'],
  },
  {
    id: '17',
    name: 'Oliver Martin',
    age: 34,
    email: 'oliver.martin@example.com',
    tags: ['security', 'cybersecurity', 'compliance'],
  },
  {
    id: '18',
    name: 'Petra Garcia',
    age: 29,
    email: 'petra.garcia@example.com',
    tags: ['data-scientist', 'ml', 'analytics'],
  },
  {
    id: '19',
    name: 'Quinn Rodriguez',
    age: 26,
    email: 'quinn.rodriguez@example.com',
    tags: ['developer', 'golang', 'microservices'],
  },
  {
    id: '20',
    name: 'Rachel Lee',
    age: 30,
    email: 'rachel.lee@example.com',
    tags: ['scrum-master', 'agile', 'facilitation'],
  },
  {
    id: '21',
    name: 'Samuel Clark',
    age: 37,
    email: 'samuel.clark@example.com',
    tags: ['architect', 'cloud', 'azure'],
  },
  {
    id: '22',
    name: 'Tina Lewis',
    age: 25,
    email: 'tina.lewis@example.com',
    tags: ['designer', 'illustration', 'graphics'],
  },
  {
    id: '23',
    name: 'Ulrich Walker',
    age: 43,
    email: 'ulrich.walker@example.com',
    tags: ['consultant', 'enterprise', 'integration'],
  },
  {
    id: '24',
    name: 'Vera Hall',
    age: 32,
    email: 'vera.hall@example.com',
    tags: ['business-analyst', 'requirements', 'documentation'],
  },
  {
    id: '25',
    name: 'William Allen',
    age: 28,
    email: 'william.allen@example.com',
    tags: ['developer', 'java', 'spring'],
  },
  {
    id: '26',
    name: 'Xara Young',
    age: 24,
    email: 'xara.young@example.com',
    tags: ['intern', 'design', 'prototyping'],
  },
  {
    id: '27',
    name: 'Yuki Hernandez',
    age: 31,
    email: 'yuki.hernandez@example.com',
    tags: ['developer', 'angular', 'typescript'],
  },
  {
    id: '28',
    name: 'Zoe King',
    age: 27,
    email: 'zoe.king@example.com',
    tags: ['marketing', 'content', 'social-media'],
  },
  {
    id: '29',
    name: 'Aaron Wright',
    age: 35,
    email: 'aaron.wright@example.com',
    tags: ['team-lead', 'mentoring', 'code-review'],
  },
  {
    id: '30',
    name: 'Bella Lopez',
    age: 26,
    email: 'bella.lopez@example.com',
    tags: ['developer', 'react-native', 'mobile'],
  },
  {
    id: '31',
    name: 'Carlos Hill',
    age: 39,
    email: 'carlos.hill@example.com',
    tags: ['database', 'postgresql', 'performance'],
  },
  {
    id: '32',
    name: 'Delia Scott',
    age: 33,
    email: 'delia.scott@example.com',
    tags: ['hr', 'recruiting', 'people-ops'],
  },
  {
    id: '33',
    name: 'Ethan Green',
    age: 28,
    email: 'ethan.green@example.com',
    tags: ['developer', 'rust', 'systems'],
  },
  {
    id: '34',
    name: 'Faith Adams',
    age: 30,
    email: 'faith.adams@example.com',
    tags: ['finance', 'budgeting', 'reporting'],
  },
  {
    id: '35',
    name: 'Gabriel Baker',
    age: 26,
    email: 'gabriel.baker@example.com',
    tags: ['developer', 'nodejs', 'api'],
  },
  {
    id: '36',
    name: 'Holly Gonzalez',
    age: 29,
    email: 'holly.gonzalez@example.com',
    tags: ['designer', 'motion-graphics', 'animation'],
  },
  {
    id: '37',
    name: 'Isaac Nelson',
    age: 34,
    email: 'isaac.nelson@example.com',
    tags: ['sales', 'b2b', 'relationships'],
  },
  {
    id: '38',
    name: 'Jasmine Carter',
    age: 27,
    email: 'jasmine.carter@example.com',
    tags: ['developer', 'php', 'laravel'],
  },
  {
    id: '39',
    name: 'Kyle Mitchell',
    age: 31,
    email: 'kyle.mitchell@example.com',
    tags: ['support', 'customer-success', 'troubleshooting'],
  },
  {
    id: '40',
    name: 'Lily Perez',
    age: 25,
    email: 'lily.perez@example.com',
    tags: ['content-writer', 'documentation', 'technical-writing'],
  },
  {
    id: '41',
    name: 'Marcus Roberts',
    age: 40,
    email: 'marcus.roberts@example.com',
    tags: ['operations', 'logistics', 'efficiency'],
  },
  {
    id: '42',
    name: 'Nora Turner',
    age: 28,
    email: 'nora.turner@example.com',
    tags: ['developer', 'c#', 'dotnet'],
  },
  {
    id: '43',
    name: 'Oscar Phillips',
    age: 36,
    email: 'oscar.phillips@example.com',
    tags: ['legal', 'compliance', 'contracts'],
  },
  {
    id: '44',
    name: 'Penny Campbell',
    age: 24,
    email: 'penny.campbell@example.com',
    tags: ['social-media', 'community', 'engagement'],
  },
  {
    id: '45',
    name: 'Quincy Parker',
    age: 32,
    email: 'quincy.parker@example.com',
    tags: ['researcher', 'innovation', 'r&d'],
  },
  {
    id: '46',
    name: 'Rosa Evans',
    age: 29,
    email: 'rosa.evans@example.com',
    tags: ['developer', 'kotlin', 'android'],
  },
  {
    id: '47',
    name: 'Steve Edwards',
    age: 38,
    email: 'steve.edwards@example.com',
    tags: ['consultant', 'transformation', 'change-management'],
  },
  {
    id: '48',
    name: 'Tara Collins',
    age: 27,
    email: 'tara.collins@example.com',
    tags: ['designer', 'accessibility', 'inclusive-design'],
  },
  {
    id: '49',
    name: 'Uri Stewart',
    age: 33,
    email: 'uri.stewart@example.com',
    tags: ['blockchain', 'cryptocurrency', 'web3'],
  },
  {
    id: '50',
    name: 'Violet Morris',
    age: 30,
    email: 'violet.morris@example.com',
    tags: ['product-manager', 'roadmap', 'stakeholders'],
  },
];
