export enum EnvVariables {
  NODE_ENV = 'NODE_ENV',
  ENVIRONMENT = 'ENVIRONMENT',
  // Just for Development
  AUTO_LOG_IN_DEV_USER = 'AUTO_LOG_IN_DEV_USER',
  DEV_USER_ROLE = 'DEV_USER_ROLE',
  DEV_USER_ID = 'DEV_USER_ID',
  DEV_USER_EMAIL = 'DEV_USER_EMAIL',
  DEV_USER_ORG_CODE = 'DEV_USER_ORG_CODE',
  DEV_USER_ORG_CODES = 'DEV_USER_ORG_CODES',
  DEV_USER_FINDERPRINT = 'DEV_USER_FINDERPRINT',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  TIME_BEFORE_SESSION_EXPIRE_MS = 'TIME_BEFORE_SESSION_EXPIRE_MS',
  SERVER_TOKEN_EXPIRATION_MS = 'SERVER_TOKEN_EXPIRATION_MS',
}
