import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { IMdSyncEvent } from '@ai-nx-starter/types';
import { BaseApiService } from '../../../services/base-api.service';
import { AppConfigService } from '../../../services/app-config.service';

/**
 * ApiSyncEventsService - Angular service for SyncEventsController
 * Auto-generated by tools/api-client-generator
 */
@Injectable({
  providedIn: 'root'
})
export class ApiSyncEventsService extends BaseApiService {

  constructor(http: HttpClient, config: AppConfigService) {
    super(http, config);
  }

  /**
   * emitEvent - POST events/emit
   *
   * @param event - Body parameter
   * @returns Observable<{ success: boolean; message: string; }>
   */
  emitEvent(event: IMdSyncEvent): Observable<{ success: boolean; message: string; }> {
    return this.http.post<{ success: boolean; message: string; }>(
      `${this.BASE_URL}/events/emit`,
      event
    );
  }

}
