import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { UiAppContextDto } from '@medorion/types';
import { BaseApiService } from '../../services/base-api.service';
import { AppConfigService } from '../../services/app-config.service';

/**
 * ApiAuthService - Angular service for AuthController
 * Auto-generated by gen-api-client.ts
 */
@Injectable({
  providedIn: 'root'
})
export class ApiAuthService extends BaseApiService {

  constructor(http: HttpClient, config: AppConfigService) {
    super(http, config);
  }

  /**
   * getUiAppContext - GET auth/ui-app-context
   *
   * @returns Observable<UiAppContextDto>
   */
  getUiAppContext(): Observable<UiAppContextDto> {
    return this.http.get<UiAppContextDto>(
      `${this.BASE_URL}/auth/ui-app-context`,
    );
  }

}
