import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { UIAppContextDto, ExternalLoginDto } from '@medorion/types';
import { BaseApiService } from '../../services/base-api.service';
import { AppConfigService } from '../../services/app-config.service';

/**
 * ApiAuthService - Angular service for AuthController
 * Auto-generated by gen-api-client.ts
 */
@Injectable({
  providedIn: 'root',
})
export class ApiAuthService extends BaseApiService {
  constructor(http: HttpClient, config: AppConfigService) {
    super(http, config);
  }

  /**
   * getUiAppContext - GET auth/ui-app-context
   *
   * @returns Observable<UIAppContextDto>
   */
  getUiAppContext(): Observable<UIAppContextDto> {
    return this.http.get<UIAppContextDto>(`${this.BASE_URL}/auth/ui-app-context`);
  }

  /**
   * externalLogin - POST auth//external-login
   *
   * @param userLoginDto - Body parameter
   * @returns Observable<void>
   */
  externalLogin(userLoginDto: ExternalLoginDto): Observable<void> {
    return this.http.post<void>(`${this.BASE_URL}/auth/external-login`, userLoginDto);
  }

  /**
   * externalLogout - GET auth//external-logout
   *
   * @returns Observable<void>
   */
  externalLogout(): Observable<void> {
    return this.http.get<void>(`${this.BASE_URL}/auth/external-logout`);
  }
}
